### ISSUE TITLE
[Bug] Union Failure, Different Datatypes

### ISSUE THREAD

**Issue by moodybox** [fivetran/dbt_sage_intacct#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In the union for ap_ar_enhanced, there are incompatible types. Department ID seems to fail here. If you cast the department ID to a string, then the model runs without issue.

### Relevant error log or model output

```shell
"Writing runtime sql for node "model.sage_intacct.sage_intacct__ap_ar_enhanced"
BigQuery adapter: https://console.cloud.google.com/bigquery?project=...
BigQuery adapter: Retry attempt 1 of 1 after error: BadRequest('Column 13 in UNION ALL has incompatible types: STRING, INT64 at [143:5]')"
```

### Expected behavior

Here is one of the offending lines:

`ap_bill_item.department_id,`

And here is the fix:

`cast(ap_bill_item.department_id as string) as department_id,`

The other offending line also requires a similar fix:
```

ar_invoice_item.department_id, ->
cast(ar_invoice_item.department_id as string) as department_id,
```

### dbt Project configurations

I have the default setting of true for  sage_intacct__using_invoices, sage_intacct__using_bills.

### Package versions

From packages.yml:
  - package: fivetran/sage_intacct
    version: 0.2.2

### What database are you using dbt with?

bigquery

### dbt Version

1.6, for some reason dbt --version in the IDE isn't working.

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by moodybox** [comment]
This is my first time using the package. 

I think that fix will definitely work. I'll look forward to that fix coming down the pipeline.

**Comment by fivetran-jamie** [comment]
this is in v0.2.1 of the source package! so the transform package will automatically pick it up
