### ISSUE TITLE
[Bug] Timestamp not recognized error when generating datespine

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_sage_intacct#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In cases when there are no transactions yet in the General Ledger model the downstream datespine model will fail as there is not a [minimum date](https://github.com/fivetran/dbt_sage_intacct/blob/241050f77b95f5dd49d2d4fa1b8e98718e745458/models/intermediate/int_sage_intacct__general_ledger_date_spine.sql#L5) to choose from. Thus results in the below provided error message.

To address this we will need to apply a coalesce to this model to ensure a date is specified even if there are no transactions in the General Ledger model. We have made similar [updates to QuickBooks](https://github.com/fivetran/dbt_quickbooks/compare/v0.12.2...v0.12.3) where we can apply a [similar update](https://github.com/fivetran/dbt_quickbooks/blob/86778a24d08da7a5dc4571b20f97bcf35c33da59/models/intermediate/int_quickbooks__general_ledger_date_spine.sql#L6-L8) to ensure users are able to see a successful run before transactions are seen in the General Ledger model.

### Relevant error log or model output

```shell
database error in model int_sage_intacct__general_ledger_date_spine (models/intermediate/int_sage_intacct__general_ledger_date_spine.sql) 100035 (22007): timestamp 'none' is not recognized
```

### Expected behavior

The models are able to succeed before transactions are available.

### dbt Project configurations

Default

### Package versions

v0.4.0

### What database are you using dbt with?

snowflake

### dbt Version

v1.8.1

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-avinash** [comment]
[Issue resolved in the above PR](https://github.com/fivetran/dbt_sage_intacct/pull/24).
